### ISSUE TITLE
Manage Tomee Spanish Translations 2020/Q1

### ISSUE THREAD

**Issue by emecas** [emecas/commitit#27]
- [x] [TOMEE-2786](https://issues.apache.org/jira/browse/TOMEE-2786) Spanish translation for vaadin-vxx-simple example [ PR # 630 ](https://github.com/apache/tomee/pull/630) [merged]
 - [x] [TOMEE-2794](https://issues.apache.org/jira/browse/TOMEE-2794) Spanish translation for vaadin-v08-simple example [ PR # 631 ](https://github.com/apache/tomee/pull/631) [merged]
 - [x] [TOMEE-2795](https://issues.apache.org/jira/browse/TOMEE-2795) Spanish translation for vaadin-v10-simple example [ PR # 632 ](https://github.com/apache/tomee/pull/632) [merged]

**Comment by emecas** [comment]
Release Notes - TomEE - Version 8.0.2
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12312320&version=12346650
