### ISSUE TITLE
Manage Tomee Spanish Translations 2020/Q3

### ISSUE THREAD

**Issue by emecas** [emecas/commitit#61]
- [x] [TOMEE-2892](https://issues.apache.org/jira/browse/TOMEE-2892) Spanish translation for injection-of-entitymanager example [ PR#699 ](https://github.com/apache/tomee/pull/699) [merged]
 - [x] [TOMEE-2898](https://issues.apache.org/jira/browse/TOMEE-2898) Spanish translation for injection-of-env-entry example [ PR#705 ](https://github.com/apache/tomee/pull/705) [merged]
 - [x] [TOMEE-2899](https://issues.apache.org/jira/browse/TOMEE-2899) Spanish translation for  injection-of-env-entry example and adjustments example [ PR#707 ](https://github.com/apache/tomee/pull/707) [merged]
